//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
// Created via this command line: "C:\Users\vinicius.basile\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://vinnyunity.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"VinnyB.RetrieveActions.Earlybounds" /out:"C:\Users\vinicius.basile\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

namespace VinnyB.RetrieveActions.Earlybounds
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ComponentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletedUnpublished = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_BusinessProcessType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessFlow = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaskFlow = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Action = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessProcessFlow = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessRule = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dialog = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModernFlow = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserved = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Background = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Realtime = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_ProcessTriggerScope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_RunAs
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallingUser = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Scope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessUnit = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ParentChildBusinessUnits = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postoperation = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preoperation = 20,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activated = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activation = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Definition = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Template = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_UIFlowType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Desktop = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerShell = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SeleniumIDE = 1,
	}
}
